package com.se.program.mapper;

import com.se.program.entities.prescription;
import com.se.program.entities.prescriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface prescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    long countByExample(prescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int deleteByExample(prescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int insert(prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int insertSelective(prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    List<prescription> selectByExample(prescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    prescription selectByPrimaryKey(Integer prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") prescription record, @Param("example") prescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") prescription record, @Param("example") prescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(prescription record);
}