package com.se.program.mapper;

import com.se.program.entities.register;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@ResponseBody
@Repository
public interface registerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    int insert(register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    int insertSelective(register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    register selectByPrimaryKey(Integer registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(register record);

    int selectMaxCount();

    String selectRegisterImgByFormId(Integer formId);

    List<Integer> selectRegIdByFormId(Integer FormId);

}