package com.se.program.mapper;

import com.se.program.entities.SendRecord;
import com.se.program.entities.SendRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    long countByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    int deleteByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    int insert(SendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    int insertSelective(SendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    List<SendRecord> selectByExample(SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SendRecord record, @Param("example") SendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SendRecord record, @Param("example") SendRecordExample example);
}