package com.se.program.entities;

public class bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_id
     *
     * @mbg.generated
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_cost
     *
     * @mbg.generated
     */
    private Float billCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_selfcost
     *
     * @mbg.generated
     */
    private Float billSelfcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_prescription_image
     *
     * @mbg.generated
     */
    private String billPrescriptionImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_image
     *
     * @mbg.generated
     */
    private String billImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_hospital
     *
     * @mbg.generated
     */
    private String billHospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_department
     *
     * @mbg.generated
     */
    private String billDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.register_id
     *
     * @mbg.generated
     */
    private Integer registerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_id
     *
     * @return the value of bill.bill_id
     *
     * @mbg.generated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_id
     *
     * @param billId the value for bill.bill_id
     *
     * @mbg.generated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_cost
     *
     * @return the value of bill.bill_cost
     *
     * @mbg.generated
     */
    public Float getBillCost() {
        return billCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_cost
     *
     * @param billCost the value for bill.bill_cost
     *
     * @mbg.generated
     */
    public void setBillCost(Float billCost) {
        this.billCost = billCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_selfcost
     *
     * @return the value of bill.bill_selfcost
     *
     * @mbg.generated
     */
    public Float getBillSelfcost() {
        return billSelfcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_selfcost
     *
     * @param billSelfcost the value for bill.bill_selfcost
     *
     * @mbg.generated
     */
    public void setBillSelfcost(Float billSelfcost) {
        this.billSelfcost = billSelfcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_prescription_image
     *
     * @return the value of bill.bill_prescription_image
     *
     * @mbg.generated
     */
    public String getBillPrescriptionImage() {
        return billPrescriptionImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_prescription_image
     *
     * @param billPrescriptionImage the value for bill.bill_prescription_image
     *
     * @mbg.generated
     */
    public void setBillPrescriptionImage(String billPrescriptionImage) {
        this.billPrescriptionImage = billPrescriptionImage == null ? null : billPrescriptionImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_image
     *
     * @return the value of bill.bill_image
     *
     * @mbg.generated
     */
    public String getBillImage() {
        return billImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_image
     *
     * @param billImage the value for bill.bill_image
     *
     * @mbg.generated
     */
    public void setBillImage(String billImage) {
        this.billImage = billImage == null ? null : billImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_hospital
     *
     * @return the value of bill.bill_hospital
     *
     * @mbg.generated
     */
    public String getBillHospital() {
        return billHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_hospital
     *
     * @param billHospital the value for bill.bill_hospital
     *
     * @mbg.generated
     */
    public void setBillHospital(String billHospital) {
        this.billHospital = billHospital == null ? null : billHospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_department
     *
     * @return the value of bill.bill_department
     *
     * @mbg.generated
     */
    public String getBillDepartment() {
        return billDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_department
     *
     * @param billDepartment the value for bill.bill_department
     *
     * @mbg.generated
     */
    public void setBillDepartment(String billDepartment) {
        this.billDepartment = billDepartment == null ? null : billDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.form_id
     *
     * @return the value of bill.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.form_id
     *
     * @param formId the value for bill.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.register_id
     *
     * @return the value of bill.register_id
     *
     * @mbg.generated
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.register_id
     *
     * @param registerId the value for bill.register_id
     *
     * @mbg.generated
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }
}