package com.se.program.entities;

public class bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_id
     *
     * @mbg.generated
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_image
     *
     * @mbg.generated
     */
    private String billImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_id
     *
     * @return the value of bill.bill_id
     *
     * @mbg.generated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_id
     *
     * @param billId the value for bill.bill_id
     *
     * @mbg.generated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_image
     *
     * @return the value of bill.bill_image
     *
     * @mbg.generated
     */
    public String getBillImage() {
        return billImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_image
     *
     * @param billImage the value for bill.bill_image
     *
     * @mbg.generated
     */
    public void setBillImage(String billImage) {
        this.billImage = billImage == null ? null : billImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.form_id
     *
     * @return the value of bill.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.form_id
     *
     * @param formId the value for bill.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}