package com.se.program.entities;

public class changehospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changehospital.changehospital_id
     *
     * @mbg.generated
     */
    private Integer changehospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changehospital.changehospital_image
     *
     * @mbg.generated
     */
    private String changehospitalImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changehospital.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changehospital.changehospital_id
     *
     * @return the value of changehospital.changehospital_id
     *
     * @mbg.generated
     */
    public Integer getChangehospitalId() {
        return changehospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changehospital.changehospital_id
     *
     * @param changehospitalId the value for changehospital.changehospital_id
     *
     * @mbg.generated
     */
    public void setChangehospitalId(Integer changehospitalId) {
        this.changehospitalId = changehospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changehospital.changehospital_image
     *
     * @return the value of changehospital.changehospital_image
     *
     * @mbg.generated
     */
    public String getChangehospitalImage() {
        return changehospitalImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changehospital.changehospital_image
     *
     * @param changehospitalImage the value for changehospital.changehospital_image
     *
     * @mbg.generated
     */
    public void setChangehospitalImage(String changehospitalImage) {
        this.changehospitalImage = changehospitalImage == null ? null : changehospitalImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changehospital.form_id
     *
     * @return the value of changehospital.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changehospital.form_id
     *
     * @param formId the value for changehospital.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}