package com.se.program.entities;

public class department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_oldname
     *
     * @mbg.generated
     */
    private String departmentOldname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_state
     *
     * @mbg.generated
     */
    private String departmentState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_oldname
     *
     * @return the value of department.department_oldname
     *
     * @mbg.generated
     */
    public String getDepartmentOldname() {
        return departmentOldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_oldname
     *
     * @param departmentOldname the value for department.department_oldname
     *
     * @mbg.generated
     */
    public void setDepartmentOldname(String departmentOldname) {
        this.departmentOldname = departmentOldname == null ? null : departmentOldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_state
     *
     * @return the value of department.department_state
     *
     * @mbg.generated
     */
    public String getDepartmentState() {
        return departmentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_state
     *
     * @param departmentState the value for department.department_state
     *
     * @mbg.generated
     */
    public void setDepartmentState(String departmentState) {
        this.departmentState = departmentState == null ? null : departmentState.trim();
    }
}