package com.se.program.entities;

import java.util.Date;

public class form {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_time
     *
     * @mbg.generated
     */
    private Date formTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_kind
     *
     * @mbg.generated
     */
    private Integer formKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.hospital
     *
     * @mbg.generated
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_text
     *
     * @mbg.generated
     */
    private String formText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.hospital_department
     *
     * @mbg.generated
     */
    private String hospitalDepartment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_id
     *
     * @return the value of form.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_id
     *
     * @param formId the value for form.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_time
     *
     * @return the value of form.form_time
     *
     * @mbg.generated
     */
    public Date getFormTime() {
        return formTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_time
     *
     * @param formTime the value for form.form_time
     *
     * @mbg.generated
     */
    public void setFormTime(Date formTime) {
        this.formTime = formTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_kind
     *
     * @return the value of form.form_kind
     *
     * @mbg.generated
     */
    public Integer getFormKind() {
        return formKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_kind
     *
     * @param formKind the value for form.form_kind
     *
     * @mbg.generated
     */
    public void setFormKind(Integer formKind) {
        this.formKind = formKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.hospital
     *
     * @return the value of form.hospital
     *
     * @mbg.generated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.hospital
     *
     * @param hospital the value for form.hospital
     *
     * @mbg.generated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_text
     *
     * @return the value of form.form_text
     *
     * @mbg.generated
     */
    public String getFormText() {
        return formText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_text
     *
     * @param formText the value for form.form_text
     *
     * @mbg.generated
     */
    public void setFormText(String formText) {
        this.formText = formText == null ? null : formText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.hospital_department
     *
     * @return the value of form.hospital_department
     *
     * @mbg.generated
     */
    public String getHospitalDepartment() {
        return hospitalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.hospital_department
     *
     * @param hospitalDepartment the value for form.hospital_department
     *
     * @mbg.generated
     */
    public void setHospitalDepartment(String hospitalDepartment) {
        this.hospitalDepartment = hospitalDepartment == null ? null : hospitalDepartment.trim();
    }
}