package com.se.program.entities;

import java.util.Date;

public class operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_id
     *
     * @mbg.generated
     */
    private Integer operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_time
     *
     * @mbg.generated
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.register_percentage
     *
     * @mbg.generated
     */
    private Float registerPercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.medical_percentage
     *
     * @mbg.generated
     */
    private Float medicalPercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_kind
     *
     * @mbg.generated
     */
    private Integer operationKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_text
     *
     * @mbg.generated
     */
    private String operationText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_id
     *
     * @return the value of operation.operation_id
     *
     * @mbg.generated
     */
    public Integer getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_id
     *
     * @param operationId the value for operation.operation_id
     *
     * @mbg.generated
     */
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.form_id
     *
     * @return the value of operation.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.form_id
     *
     * @param formId the value for operation.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_time
     *
     * @return the value of operation.operation_time
     *
     * @mbg.generated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_time
     *
     * @param operationTime the value for operation.operation_time
     *
     * @mbg.generated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.amount
     *
     * @return the value of operation.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.amount
     *
     * @param amount the value for operation.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.register_percentage
     *
     * @return the value of operation.register_percentage
     *
     * @mbg.generated
     */
    public Float getRegisterPercentage() {
        return registerPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.register_percentage
     *
     * @param registerPercentage the value for operation.register_percentage
     *
     * @mbg.generated
     */
    public void setRegisterPercentage(Float registerPercentage) {
        this.registerPercentage = registerPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.medical_percentage
     *
     * @return the value of operation.medical_percentage
     *
     * @mbg.generated
     */
    public Float getMedicalPercentage() {
        return medicalPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.medical_percentage
     *
     * @param medicalPercentage the value for operation.medical_percentage
     *
     * @mbg.generated
     */
    public void setMedicalPercentage(Float medicalPercentage) {
        this.medicalPercentage = medicalPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.admin_id
     *
     * @return the value of operation.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.admin_id
     *
     * @param adminId the value for operation.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_kind
     *
     * @return the value of operation.operation_kind
     *
     * @mbg.generated
     */
    public Integer getOperationKind() {
        return operationKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_kind
     *
     * @param operationKind the value for operation.operation_kind
     *
     * @mbg.generated
     */
    public void setOperationKind(Integer operationKind) {
        this.operationKind = operationKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_text
     *
     * @return the value of operation.operation_text
     *
     * @mbg.generated
     */
    public String getOperationText() {
        return operationText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_text
     *
     * @param operationText the value for operation.operation_text
     *
     * @mbg.generated
     */
    public void setOperationText(String operationText) {
        this.operationText = operationText == null ? null : operationText.trim();
    }
}