package com.se.program.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class operationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public operationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperationIdIsNull() {
            addCriterion("operation_id is null");
            return (Criteria) this;
        }

        public Criteria andOperationIdIsNotNull() {
            addCriterion("operation_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperationIdEqualTo(Integer value) {
            addCriterion("operation_id =", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdNotEqualTo(Integer value) {
            addCriterion("operation_id <>", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdGreaterThan(Integer value) {
            addCriterion("operation_id >", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operation_id >=", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdLessThan(Integer value) {
            addCriterion("operation_id <", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdLessThanOrEqualTo(Integer value) {
            addCriterion("operation_id <=", value, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdIn(List<Integer> values) {
            addCriterion("operation_id in", values, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdNotIn(List<Integer> values) {
            addCriterion("operation_id not in", values, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdBetween(Integer value1, Integer value2) {
            addCriterion("operation_id between", value1, value2, "operationId");
            return (Criteria) this;
        }

        public Criteria andOperationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operation_id not between", value1, value2, "operationId");
            return (Criteria) this;
        }

        public Criteria andFormIdIsNull() {
            addCriterion("form_id is null");
            return (Criteria) this;
        }

        public Criteria andFormIdIsNotNull() {
            addCriterion("form_id is not null");
            return (Criteria) this;
        }

        public Criteria andFormIdEqualTo(Integer value) {
            addCriterion("form_id =", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotEqualTo(Integer value) {
            addCriterion("form_id <>", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThan(Integer value) {
            addCriterion("form_id >", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("form_id >=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThan(Integer value) {
            addCriterion("form_id <", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThanOrEqualTo(Integer value) {
            addCriterion("form_id <=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdIn(List<Integer> values) {
            addCriterion("form_id in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotIn(List<Integer> values) {
            addCriterion("form_id not in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdBetween(Integer value1, Integer value2) {
            addCriterion("form_id between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotBetween(Integer value1, Integer value2) {
            addCriterion("form_id not between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiIsNull() {
            addCriterion("register_zifei is null");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiIsNotNull() {
            addCriterion("register_zifei is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiEqualTo(Integer value) {
            addCriterion("register_zifei =", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiNotEqualTo(Integer value) {
            addCriterion("register_zifei <>", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiGreaterThan(Integer value) {
            addCriterion("register_zifei >", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_zifei >=", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiLessThan(Integer value) {
            addCriterion("register_zifei <", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiLessThanOrEqualTo(Integer value) {
            addCriterion("register_zifei <=", value, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiIn(List<Integer> values) {
            addCriterion("register_zifei in", values, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiNotIn(List<Integer> values) {
            addCriterion("register_zifei not in", values, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiBetween(Integer value1, Integer value2) {
            addCriterion("register_zifei between", value1, value2, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andRegisterZifeiNotBetween(Integer value1, Integer value2) {
            addCriterion("register_zifei not between", value1, value2, "registerZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiIsNull() {
            addCriterion("bill_zifei is null");
            return (Criteria) this;
        }

        public Criteria andBillZifeiIsNotNull() {
            addCriterion("bill_zifei is not null");
            return (Criteria) this;
        }

        public Criteria andBillZifeiEqualTo(Integer value) {
            addCriterion("bill_zifei =", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiNotEqualTo(Integer value) {
            addCriterion("bill_zifei <>", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiGreaterThan(Integer value) {
            addCriterion("bill_zifei >", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiGreaterThanOrEqualTo(Integer value) {
            addCriterion("bill_zifei >=", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiLessThan(Integer value) {
            addCriterion("bill_zifei <", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiLessThanOrEqualTo(Integer value) {
            addCriterion("bill_zifei <=", value, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiIn(List<Integer> values) {
            addCriterion("bill_zifei in", values, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiNotIn(List<Integer> values) {
            addCriterion("bill_zifei not in", values, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiBetween(Integer value1, Integer value2) {
            addCriterion("bill_zifei between", value1, value2, "billZifei");
            return (Criteria) this;
        }

        public Criteria andBillZifeiNotBetween(Integer value1, Integer value2) {
            addCriterion("bill_zifei not between", value1, value2, "billZifei");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNull() {
            addCriterion("operation_time is null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNotNull() {
            addCriterion("operation_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeEqualTo(Date value) {
            addCriterion("operation_time =", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotEqualTo(Date value) {
            addCriterion("operation_time <>", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThan(Date value) {
            addCriterion("operation_time >", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operation_time >=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThan(Date value) {
            addCriterion("operation_time <", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThanOrEqualTo(Date value) {
            addCriterion("operation_time <=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIn(List<Date> values) {
            addCriterion("operation_time in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotIn(List<Date> values) {
            addCriterion("operation_time not in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeBetween(Date value1, Date value2) {
            addCriterion("operation_time between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotBetween(Date value1, Date value2) {
            addCriterion("operation_time not between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(String value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(String value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(String value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(String value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(String value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(String value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLike(String value) {
            addCriterion("amount like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotLike(String value) {
            addCriterion("amount not like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<String> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<String> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(String value1, String value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(String value1, String value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andOperationKindIsNull() {
            addCriterion("operation_kind is null");
            return (Criteria) this;
        }

        public Criteria andOperationKindIsNotNull() {
            addCriterion("operation_kind is not null");
            return (Criteria) this;
        }

        public Criteria andOperationKindEqualTo(Integer value) {
            addCriterion("operation_kind =", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindNotEqualTo(Integer value) {
            addCriterion("operation_kind <>", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindGreaterThan(Integer value) {
            addCriterion("operation_kind >", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("operation_kind >=", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindLessThan(Integer value) {
            addCriterion("operation_kind <", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindLessThanOrEqualTo(Integer value) {
            addCriterion("operation_kind <=", value, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindIn(List<Integer> values) {
            addCriterion("operation_kind in", values, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindNotIn(List<Integer> values) {
            addCriterion("operation_kind not in", values, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindBetween(Integer value1, Integer value2) {
            addCriterion("operation_kind between", value1, value2, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationKindNotBetween(Integer value1, Integer value2) {
            addCriterion("operation_kind not between", value1, value2, "operationKind");
            return (Criteria) this;
        }

        public Criteria andOperationTextIsNull() {
            addCriterion("operation_text is null");
            return (Criteria) this;
        }

        public Criteria andOperationTextIsNotNull() {
            addCriterion("operation_text is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTextEqualTo(String value) {
            addCriterion("operation_text =", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextNotEqualTo(String value) {
            addCriterion("operation_text <>", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextGreaterThan(String value) {
            addCriterion("operation_text >", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextGreaterThanOrEqualTo(String value) {
            addCriterion("operation_text >=", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextLessThan(String value) {
            addCriterion("operation_text <", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextLessThanOrEqualTo(String value) {
            addCriterion("operation_text <=", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextLike(String value) {
            addCriterion("operation_text like", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextNotLike(String value) {
            addCriterion("operation_text not like", value, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextIn(List<String> values) {
            addCriterion("operation_text in", values, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextNotIn(List<String> values) {
            addCriterion("operation_text not in", values, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextBetween(String value1, String value2) {
            addCriterion("operation_text between", value1, value2, "operationText");
            return (Criteria) this;
        }

        public Criteria andOperationTextNotBetween(String value1, String value2) {
            addCriterion("operation_text not between", value1, value2, "operationText");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}