package com.se.program.entities;

public class prescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_id
     *
     * @mbg.generated
     */
    private Integer prescriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_hospital
     *
     * @mbg.generated
     */
    private String prescriptionHospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_department
     *
     * @mbg.generated
     */
    private String prescriptionDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_cost
     *
     * @mbg.generated
     */
    private Integer prescriptionCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_image
     *
     * @mbg.generated
     */
    private String prescriptionImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_id
     *
     * @return the value of prescription.prescription_id
     *
     * @mbg.generated
     */
    public Integer getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_id
     *
     * @param prescriptionId the value for prescription.prescription_id
     *
     * @mbg.generated
     */
    public void setPrescriptionId(Integer prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_hospital
     *
     * @return the value of prescription.prescription_hospital
     *
     * @mbg.generated
     */
    public String getPrescriptionHospital() {
        return prescriptionHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_hospital
     *
     * @param prescriptionHospital the value for prescription.prescription_hospital
     *
     * @mbg.generated
     */
    public void setPrescriptionHospital(String prescriptionHospital) {
        this.prescriptionHospital = prescriptionHospital == null ? null : prescriptionHospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_department
     *
     * @return the value of prescription.prescription_department
     *
     * @mbg.generated
     */
    public String getPrescriptionDepartment() {
        return prescriptionDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_department
     *
     * @param prescriptionDepartment the value for prescription.prescription_department
     *
     * @mbg.generated
     */
    public void setPrescriptionDepartment(String prescriptionDepartment) {
        this.prescriptionDepartment = prescriptionDepartment == null ? null : prescriptionDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_cost
     *
     * @return the value of prescription.prescription_cost
     *
     * @mbg.generated
     */
    public Integer getPrescriptionCost() {
        return prescriptionCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_cost
     *
     * @param prescriptionCost the value for prescription.prescription_cost
     *
     * @mbg.generated
     */
    public void setPrescriptionCost(Integer prescriptionCost) {
        this.prescriptionCost = prescriptionCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_image
     *
     * @return the value of prescription.prescription_image
     *
     * @mbg.generated
     */
    public String getPrescriptionImage() {
        return prescriptionImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_image
     *
     * @param prescriptionImage the value for prescription.prescription_image
     *
     * @mbg.generated
     */
    public void setPrescriptionImage(String prescriptionImage) {
        this.prescriptionImage = prescriptionImage == null ? null : prescriptionImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.form_id
     *
     * @return the value of prescription.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.form_id
     *
     * @param formId the value for prescription.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}