package com.se.program.entities;

public class register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_id
     *
     * @mbg.generated
     */
    private Integer registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_image
     *
     * @mbg.generated
     */
    private String registerImage;

    public register() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_id
     *
     * @return the value of register.register_id
     *
     * @mbg.generated
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_id
     *
     * @param registerId the value for register.register_id
     *
     * @mbg.generated
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_image
     *
     * @return the value of register.register_image
     *
     * @mbg.generated
     */
    public String getRegisterImage() {
        return registerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_image
     *
     * @param registerImage the value for register.register_image
     *
     * @mbg.generated
     */
    public void setRegisterImage(String registerImage) {
        this.registerImage = registerImage == null ? null : registerImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.form_id
     *
     * @return the value of register.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.form_id
     *
     * @param formId the value for register.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}