package com.se.program.entities;

public class register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_id
     *
     * @mbg.generated
     */
    private Integer registerId;

    public register(Integer registerId, String registerHospital, String registerDepartment, Integer registerCost, String registerImage, String registerExplaination, Integer formId, Integer changehospitalId) {
        this.registerId = registerId;
        this.registerHospital = registerHospital;
        this.registerDepartment = registerDepartment;
        this.registerCost = registerCost;
        this.registerImage = registerImage;
        this.registerExplaination = registerExplaination;
        this.formId = formId;
        this.changehospitalId = changehospitalId;
    }

    public register() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_hospital
     *
     * @mbg.generated
     */
    private String registerHospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_department
     *
     * @mbg.generated
     */
    private String registerDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_cost
     *
     * @mbg.generated
     */
    private Integer registerCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_image
     *
     * @mbg.generated
     */
    private String registerImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.register_explaination
     *
     * @mbg.generated
     */
    private String registerExplaination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.form_id
     *
     * @mbg.generated
     */
    private Integer formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.changehospital_id
     *
     * @mbg.generated
     */
    private Integer changehospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_id
     *
     * @return the value of register.register_id
     *
     * @mbg.generated
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_id
     *
     * @param registerId the value for register.register_id
     *
     * @mbg.generated
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_hospital
     *
     * @return the value of register.register_hospital
     *
     * @mbg.generated
     */
    public String getRegisterHospital() {
        return registerHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_hospital
     *
     * @param registerHospital the value for register.register_hospital
     *
     * @mbg.generated
     */
    public void setRegisterHospital(String registerHospital) {
        this.registerHospital = registerHospital == null ? null : registerHospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_department
     *
     * @return the value of register.register_department
     *
     * @mbg.generated
     */
    public String getRegisterDepartment() {
        return registerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_department
     *
     * @param registerDepartment the value for register.register_department
     *
     * @mbg.generated
     */
    public void setRegisterDepartment(String registerDepartment) {
        this.registerDepartment = registerDepartment == null ? null : registerDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_cost
     *
     * @return the value of register.register_cost
     *
     * @mbg.generated
     */
    public Integer getRegisterCost() {
        return registerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_cost
     *
     * @param registerCost the value for register.register_cost
     *
     * @mbg.generated
     */
    public void setRegisterCost(Integer registerCost) {
        this.registerCost = registerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_image
     *
     * @return the value of register.register_image
     *
     * @mbg.generated
     */
    public String getRegisterImage() {
        return registerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_image
     *
     * @param registerImage the value for register.register_image
     *
     * @mbg.generated
     */
    public void setRegisterImage(String registerImage) {
        this.registerImage = registerImage == null ? null : registerImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.register_explaination
     *
     * @return the value of register.register_explaination
     *
     * @mbg.generated
     */
    public String getRegisterExplaination() {
        return registerExplaination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.register_explaination
     *
     * @param registerExplaination the value for register.register_explaination
     *
     * @mbg.generated
     */
    public void setRegisterExplaination(String registerExplaination) {
        this.registerExplaination = registerExplaination == null ? null : registerExplaination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.form_id
     *
     * @return the value of register.form_id
     *
     * @mbg.generated
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.form_id
     *
     * @param formId the value for register.form_id
     *
     * @mbg.generated
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.changehospital_id
     *
     * @return the value of register.changehospital_id
     *
     * @mbg.generated
     */
    public Integer getChangehospitalId() {
        return changehospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.changehospital_id
     *
     * @param changehospitalId the value for register.changehospital_id
     *
     * @mbg.generated
     */
    public void setChangehospitalId(Integer changehospitalId) {
        this.changehospitalId = changehospitalId;
    }
}