package com.se.program.entities;

import java.util.Date;

public class SendRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.user_number
     *
     * @mbg.generated
     */
    private String userNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.user_type
     *
     * @mbg.generated
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendrecord.record_state
     *
     * @mbg.generated
     */
    private Integer recordState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.record_id
     *
     * @return the value of sendrecord.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.record_id
     *
     * @param recordId the value for sendrecord.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.user_name
     *
     * @return the value of sendrecord.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.user_name
     *
     * @param userName the value for sendrecord.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.user_number
     *
     * @return the value of sendrecord.user_number
     *
     * @mbg.generated
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.user_number
     *
     * @param userNumber the value for sendrecord.user_number
     *
     * @mbg.generated
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.user_id
     *
     * @return the value of sendrecord.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.user_id
     *
     * @param userId the value for sendrecord.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.record_time
     *
     * @return the value of sendrecord.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.record_time
     *
     * @param recordTime the value for sendrecord.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.user_type
     *
     * @return the value of sendrecord.user_type
     *
     * @mbg.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.user_type
     *
     * @param userType the value for sendrecord.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendrecord.record_state
     *
     * @return the value of sendrecord.record_state
     *
     * @mbg.generated
     */
    public Integer getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendrecord.record_state
     *
     * @param recordState the value for sendrecord.record_state
     *
     * @mbg.generated
     */
    public void setRecordState(Integer recordState) {
        this.recordState = recordState;
    }
}